CREATE DATABASE SUPERSTORE_DB;
USE SUPERSTORE_DB;
    
SHOW TABLES;
    
ALTER TABLE customers
ADD PRIMARY KEY (customer_id);
    
ALTER TABLE products
ADD PRIMARY KEY (product_id);
    

ALTER TABLE orders
ADD COLUMN order_row_id INT AUTO_INCREMENT PRIMARY KEY;
    
ALTER TABLE products
ADD COLUMN product_row_id INT AUTO_INCREMENT PRIMARY KEY;
    
select *from products limit 5;
    
ALTER TABLE orders
ADD CONSTRAINT fk_customer
FOREIGN KEY (customer_id)
REFERENCES customers(customer_id);
describe customers;

select distinct(count(*))from orders;


SELECT customer_id, COUNT(*)
FROM customers
GROUP BY customer_id
HAVING COUNT(*) > 1;
SELECT *
FROM customers
WHERE customer_id IS NULL;

ALTER TABLE customers
MODIFY customer_id INT NOT NULL;
ALTER TABLE customers
ADD PRIMARY KEY (customer_id);

ALTER TABLE orders
ADD CONSTRAINT fk_customer
FOREIGN KEY (customer_id)
REFERENCES customers(customer_id);

ALTER TABLE orders
MODIFY customer_id INT;

ALTER TABLE sales
ADD CONSTRAINT fk_order
FOREIGN KEY (order_id)
REFERENCES orders(order_id);

ALTER TABLE sales
ADD CONSTRAINT fk_product
FOREIGN KEY (product_id)
REFERENCES products(product_id);

#quries
#TOTAL SALES AND PROFIT 
SELECT ROUND(SUM(SALES),2) AS TOTAL_SALES,
ROUND(SUM(PROFIT),2) AS TOTAL_PROFIT
FROM SALES;

#TOP 10 CUSTOMERS BY SALES
SELECT C.CUSTOMER_NAME,ROUND(SUM(S.SALES),2) AS TOTAL_SALES
FROM SALES S JOIN ORDERS O 
ON S.ORDER_ID=O.ORDER_ID JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME ORDER BY TOTAL_SALES DESC
LIMIT 10;

#TOP 10 PRODUCTS BY SALES
SELECT P.PRODUCT_NAME,ROUND(SUM(S.SALES),2) AS TOTAL_SALES
FROM SALES S JOIN PRODUCTS P ON S.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC LIMIT 10;

# MOST PROFITABLE PRODUCTS 
SELECT P.PRODUCT_NAME,ROUND(SUM(S.PROFIT),2) AS TOTAL_PROFIT FROM SALES S
JOIN PRODUCTS P ON S.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME ORDER BY TOTAL_PROFIT DESC LIMIT 10;

#LOSS MAKING PRODUCTS 
SELECT P.PRODUCT_NAME,ROUND(SUM(S.PROFIT),2) AS TOTAL_PROFIT FROM SALES S
JOIN PRODUCTS P ON S.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME ORDER BY TOTAL_PROFIT ASC LIMIT 10;

#SALES BY CATEGORY
SELECT P.CATEGORY,round(SUM(S.SALES),2) AS TOTAL_SALES
FROM SALES S JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY ORDER BY TOTAL_SALES DESC;

#PROFIT BY CATEGORY
SELECT P.CATEGORY,ROUND(SUM(S.PROFIT),2) AS TOTAL_PROFIT FROM SALES S
JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID 
GROUP BY P.CATEGORY ORDER BY TOTAL_PROFIT DESC;

#Sales by Sub-Category
SELECT p.sub_category, ROUND(SUM(s.sales),2) AS total_sales
FROM sales s JOIN products p ON s.product_id = p.product_id
GROUP BY p.sub_category ORDER BY total_sales DESC;

#SALES BY REGION
SELECT O.REGION,ROUND(SUM(S.SALES),2) AS TOTAL_SALES FROM SALES S
JOIN ORDERS O ON S.ORDER_ID = O.ORDER_ID
GROUP BY O.REGION ORDER BY TOTAL_SALES DESC; 

#PROFIT BY MARKET
SELECT O.MARKET,ROUND(SUM(S.PROFIT),2) AS TOTAL_PROFIT FROM SALES S 
JOIN ORDERS O ON S.ORDER_ID = O.ORDER_ID
GROUP BY O.MARKET ORDER BY TOTAL_PROFIT DESC;

#ORDERS BY SHIPPING MODE
SELECT SHIP_MODE,COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM ORDERS GROUP BY SHIP_MODE ORDER BY TOTAL_ORDERS DESC;

#SALES BY TREND YEAR
SELECT YEAR(ORDER_DATE) AS year,ROUND(SUM(S.SALES),2) AS TOTAL_SALES FROM SALES S 
JOIN ORDERS O ON S.ORDER_ID = O.ORDER_ID 
GROUP BY YEAR ORDER BY YEAR;

#MONTHLY SALES TREND
SELECT MONTH(order_date) AS month,
    ROUND(SUM(s.sales),2) AS monthly_sales
FROM sales s JOIN orders o ON s.order_id = o.order_id
GROUP BY month ORDER BY month;

#AVG DISCOUNT BY CATEGORY
SELECT P.CATEGORY,ROUND(AVG(S.DISCOUNT),2) AS AVG_DISCOUNT FROM SALES S 
JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY;

#PROFIT MARGIN BY CATEGORY
SELECT p.category,
ROUND((SUM(s.profit)/SUM(s.sales))*100,2) AS profit_margin
FROM sales s JOIN products p ON s.product_id = p.product_id
GROUP BY p.category;

#TOP COUNTRIES BY SALES
SELECT 
    O.COUNTRY, ROUND(SUM(S.SALES), 2) AS TOTAL_SALES
FROM
    SALES S
        JOIN
    ORDERS O ON S.ORDER_ID = O.ORDER_ID
GROUP BY O.COUNTRY
ORDER BY TOTAL_SALES DESC
LIMIT 10;

#SEGMENT ANALYSIS
SELECT c.segment,
ROUND(SUM(s.sales),2) AS total_sales,
ROUND(SUM(s.profit),2) AS total_profit
FROM sales s JOIN orders o ON s.order_id = o.order_id
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.segment;

#HIGH QUANTITY SOLD PRODUCTS
SELECT P.PRODUCT_NAME,SUM(S.QUANTITY) AS TOTAL_QUANTITY FROM SALES S 
JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME ORDER BY TOTAL_QUANTITY DESC LIMIT 10;

#DISCOUNT IMPACT ON PROFIT
SELECT DISCOUNT,ROUND(AVG(PROFIT),2) AS AVG_PROFIT
FROM SALES 
GROUP BY DISCOUNT ORDER BY DISCOUNT;

#BASIC KPI QUERY
SELECT
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit,
    ROUND(AVG(discount),2) AS avg_discount,
    COUNT(DISTINCT order_id) AS total_orders
FROM sales;

show tables;